name: Hello world CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello_world
        run: echo "Hello World"
        shell: cmd

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye
        run: echo "Goodbye"
        shell: cmd
